version: '3'

services:
  backend:
    build: .
    image: backend
    container_name: backend
    env_file:
      - .env_backend
    ports:
      - "8080:8080"
    hostname: backend
    depends_on:
      - mongodb
    networks:
      - nosql
    restart: always

  mongodb:
    image: mongo:5.0.3
    container_name: mongodb
    hostname: mongodb-host
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGO_INITDB_DATABASE=example
    ports:
      - "27017:27017"
    networks:
      - nosql
    volumes:
      - ./data/init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    restart: always

networks:
  nosql:
    driver: bridge
